name: storyverse_studio
description: "Cross-platform Flutter app with Firebase OTP authentication and REST API CRUD operations."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - .env
